name: test
on: [push, pull_request]
jobs:
  xenial:
    container: swift:5.3-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
